### ISSUE TITLE
Implement Challenge #7 :  🎁 SVG NFT 🎫 Building Cohort Challenge

### ISSUE THREAD

**Issue by Ifechukwudaniel** [scaffold-eth/se-2-challenges#20]
TODO : 

- [ ]  Contracts 
- [ ]  UI 
- [ ] Readme 
- [ ] Tests

**Comment by cleanerzkp** [comment]
@Pabl0cks @Ifechukwudaniel 
is this still active?
can I help with that?
currently link from speedrunethereum for challange 6 and 7 directs to telegram group instead of the actual challange page
👛 Multisig Wallet Challenge
is easier fix since it's github repo already has all the content that can be put on the page in the readme 
🎁 SVG NFT 🎫 Building Cohort Challenge
doesn't, unless it's somewhere I don't see or outdated

**Comment by Pabl0cks** [comment]
> @Pabl0cks @Ifechukwudaniel
is this still active?
can I help with that?
currently link from speedrunethereum for challange 6 and 7 directs to telegram group instead of the actual challange page
👛 Multisig Wallet Challenge
is easier fix since it's github repo already has all the content that can be put on the page in the readme
🎁 SVG NFT 🎫 Building Cohort Challenge
doesn't, unless it's somewhere I don't see or outdated

Thank you @cleanerzkp for offering your help on this! 🙏

Challenge 6 (Multisig) and Challenge 7 (SVG NFT) are a bit different because there is no autograder for them, so users just submit the build on their BG profile. Challenge 6 branch serves as inspiration for others to build their own Multisig, that's why the workflow goes through Telegram first.

@rin-st has worked on most migrations, not sure if he started working on this one too. Let us check the status on the migration and we'll get back to you soon!

**Comment by rin-st** [comment]
Hi @cleanerzkp !

I'm already working on the migration, and I think I can handle it. Thank you for wanting to help!

**Comment by Pabl0cks** [comment]
Merged in #184
