### ISSUE TITLE
balanceOf doesn't work on Sepolia

### ISSUE THREAD

**Issue by fabiobozzo** [scaffold-eth/se-2-challenges#226]
I followed the speed run challenge #0 step-by-step.  
I transferred to the burner wallet below both from a public faucet and my own sepolia EoA:  
https://sepolia.etherscan.io/address/0xc39845BF85DD5C10abEc0872410dA7466F87F6C7

The balance remains zero, therefore I can't deploy. 
```
➜  challenge-0-simple-nft git:(challenge-0-simple-nft) ✗ yarn account  --network sepolia

Public address: 0xc39845BF85DD5C10abEc0872410dA7466F87F6C7 

-- localhost -- 📡
   balance: 0
   nonce: 0
-- mainnet -- 📡
   balance: 0
   nonce: 0
-- sepolia -- 📡
   balance: 0
   nonce: 0
```

**Comment by technophile-04** [comment]
Hey @fabiobozzo thanks! I think this might be some public RPC issue which we are using and which is not getting latest data from blockchain. 

If you run `yarn deploy --network sepolia` it should deploy since your account [0xc39845BF85DD5C10abEc0872410dA7466F87F6C7](https://sepolia.etherscan.io/address/0xc39845BF85DD5C10abEc0872410dA7466F87F6C7) already have some balance
