### ISSUE TITLE
Challenge 4 - Invalid Inputs

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/se-2-challenges#44]
- [ ] The ethToToken, Deposit, and Withdraw inputs will only allow a '.' if you first type in a 0.  We should allow them to type something like '.5' instead of forcing '0.5'.

- [ ] The tokenToEth input throws the following error when anything other than a number is entered, including a '.'
![image](https://github.com/scaffold-eth/se-2-challenges/assets/12072395/babd96d2-01b2-46a0-b1bb-baa1e8b4fa50)

This should behave in the same way the other inputs do where if you type a non number or decimal it omits it.

**Comment by mertcanciy** [comment]
> * [ ]  The ethToToken, Deposit, and Withdraw inputs will only allow a '.' if you first type in a 0.  We should allow them to type something like '.5' instead of forcing '0.5'.
> * [ ]  The tokenToEth input throws the following error when anything other than a number is entered, including a '.'
>   ![image](https://user-images.githubusercontent.com/12072395/257947449-babd96d2-01b2-46a0-b1bb-baa1e8b4fa50.png)
> 
> This should behave in the same way the other inputs do where if you type a non number or decimal it omits it.

for ethToToken, Deposit, and Withdraw inputs, they are using scaffold-eth's EtherInput component and also tokenToEth is using IntegerInput component. Since they are coming as default and as a part of SE-2, I couldn't know if I should touch them. Shall I try to change these components or I can try to fix without touching the components or maybe Shiv or Carlos can take a look at these components if they built these ones

**Comment by technophile-04** [comment]
> for ethToToken, Deposit, and Withdraw inputs, they are using scaffold-eth's EtherInput component 

Yup this is something we can handle at SE-2, but I have fixed it at #53 

> also tokenToEth is using IntegerInput component. 

Regarding this and `hydration error` that Zak got, Since you have updated `IntegerInput` to act as normal input (passing `hiddendSuffix`) and manually parsing the value in `useScaffoldContractWrite` hook we need to handle it while passing 

Fixed it at #53 🙌

**Comment by technophile-04** [comment]
Closing this since #53 🙌
